name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        **Before submitting, please check:**
        - Have you read the [FAQ Wiki](https://github.com/HexaEngine/Hexa.NET.ImGui/wiki/FAQ)?
        - Have you searched [existing issues](https://github.com/HexaEngine/Hexa.NET.ImGui/issues)?
        - Are you using the latest version?

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have read the [FAQ Wiki](https://github.com/HexaEngine/Hexa.NET.ImGui/wiki/FAQ)
          required: true
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I am using the latest version of Hexa.NET.ImGui
          required: true

  - type: input
    id: version
    attributes:
      label: Hexa.NET.ImGui Version
      description: What version are you using?
      placeholder: "e.g., 2.2.9"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize ImGui with...
        2. Call function...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: csharp
      placeholder: |
        // Your code here

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      options:
        - All
        - Windows
        - Linux
        - macOS
        - Android
        - Other
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: What .NET version are you using?
      placeholder: "e.g., net8.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)