name: Feature Request
description: Suggest a feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        
        **Before submitting, please check:**
        - Have you read the [README features list](https://github.com/HexaEngine/Hexa.NET.ImGui#features)?
        - Have you checked the [FAQ Wiki](https://github.com/HexaEngine/Hexa.NET.ImGui/wiki/FAQ) to see if this already exists?
        - Have you searched [existing issues](https://github.com/HexaEngine/Hexa.NET.ImGui/issues)?
        
        **Note:** Many features you might request already exist:
        - **Docking/Multi-viewport support** - Already included (docking branch is default)
        - **DockBuilder APIs** - Available via `ImGuiP` (see FAQ)
        - **ImGui internals** - Accessible via `ImGuiP` namespace
        - **Multiple backends** - Available in `Hexa.NET.ImGui.Backends` package

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have read the [README features list](https://github.com/HexaEngine/Hexa.NET.ImGui#features)
          required: true
        - label: I have read the [FAQ Wiki](https://github.com/HexaEngine/Hexa.NET.ImGui/wiki/FAQ)
          required: true
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: I have verified this feature doesn't already exist in the package
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What are you trying to accomplish?
      placeholder: I'm trying to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, code examples, or screenshots about the feature request